#!/bin/dash
if ! [ -e ".legit" ]
then
    printf "legit-add: error: no .legit directory containing legit repository exists\n"
    exit 0
fi

for file in $@
do
    if [ -e "./$file" ];then
        cp $file .legit/index
    elif [ -e .legit/index/$file ];then
        rm .legit/index/$file
    else
        printf "legit-add: error: can not open 'non_existent_file'\n"
        exit 0
    fi
done
